services:
  app:
    depends_on:
      - mongo
      - redis
    image: gkv
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017/gkv
      REDIS_URL: redis://redis:6379
      JWT_SECRET: 123456789
      SALT: 10
      URL: http://localhost:8080
      ADMIN_USER_NAME: user
      ADMIN_USER_PASS: 123456
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
    volumes:
      - mongo:/data/mongo
  redis:
    image: redis
    restart: always
    ports:
      - 6379
    volumes:
      - redis:/data/redis
volumes:
  mongo:
  redis:
